### ISSUE TITLE
When will vite-app be supported 

### ISSUE THREAD

**Issue by Squall2017** [samydoesit/vue-turbo-starter#374]

**Comment by samydoesit** [comment]
What do you mean by vue-app?

**Comment by Squall2017** [comment]
apps currently include the nuxt project, I mean vite vue project when can it be supported, and it would be better if it could be combined with vitesse.

**Comment by Squall2017** [comment]
> What do you mean by vite-app?
apps currently include the nuxt project, I mean vite vue project when can it be supported, and it would be better if it could be combined with vitesse.

**Comment by samydoesit** [comment]
This should already be supported. You can simply add "vitesse" to the project.
