### ISSUE TITLE
storybook error

### ISSUE THREAD

**Issue by Squall2017** [samydoesit/vue-turbo-starter#415]
[vite] Internal server error: ENOENT: no such file or directory, open 'D:\packages\ui\src\components\button\Button.stories.ts'

**Comment by Squall2017** [comment]
![image](https://user-images.githubusercontent.com/29035005/220269363-8831f817-3c00-4cfe-9b5c-a7f37dc6ac14.png)

**Comment by Squall2017** [comment]
![image](https://user-images.githubusercontent.com/29035005/220270100-20d6c81f-435e-4bc0-b13e-f8a7ac6d8992.png)

**Comment by samydoesit** [comment]
Hi @Squall2017 can you provide some more information?

Is the file actually there? The path looks a bit strange but if you placed the files there it should work.

If you run this on a windows machine you need to [Install WSL] (https://learn.microsoft.com/de-de/windows/wsl/install) and run it inside.

**Comment by Squall2017** [comment]
> Hi @Squall2017 can you provide some more information?
> 
> Is the file actually there? The path looks a bit strange but if you placed the files there it should work.
> 
> If you run this on a windows machine you need to [Install WSL](https://learn.microsoft.com/de-de/windows/wsl/install) and run it inside.

Thank you for your reply, I run this on a windows machine, but when I start project dev, the storybook find error path, I don't know why. The project structure has not changed.

**Comment by Squall2017** [comment]
> Hi @Squall2017 can you provide some more information?
> 
> Is the file actually there? The path looks a bit strange but if you placed the files there it should work.
> 
> If you run this on a windows machine you need to [Install WSL](https://learn.microsoft.com/de-de/windows/wsl/install) and run it inside.

Thank you for your reply, I run this on a windows machine, but when I start project dev, the storybook find error path, I don't know why. The project structure has not changed.

**Comment by samydoesit** [comment]
Are you running it inside a WSL Container?

**Comment by Squall2017** [comment]
> Are you running it inside a WSL Container?

It works, thanks

**Comment by samydoesit** [comment]
Great :)

closing here.

**Comment by funkel1989** [comment]
@samydoesit just curious, why does this only work in wsl? it is a pathing issue with different direction / vs \ or something else?

**Comment by samydoesit** [comment]
I think it is due to pnpm's use of symlinks to link dependencies, which may not behave consistently on Windows.

**Comment by samydoesit** [comment]
@funkel1989 I think it is due to pnpm's use of symlinks to link dependencies, which may not behave consistently on Windows.
